name: local
variables:
  - name: baseUrl
    value: http://localhost:8080
  - name: restUrl
    value: "{{baseUrl}}/rest"
  - name: soldatId
    value: "1"
  - name: keycloakBaseUrl
    value: http://localhost:8880
  - name: realm
    value: suprise
  - name: oidcIssuerUrl
    value: "{{keycloakBaseUrl}}/realms/{{realm}}"
  - name: oidcTokenUrl
    value: "{{oidcIssuerUrl}}/protocol/openid-connect/token"
  - name: clientId
    value: suprise-client
  - secret: true
    name: clientSecret
  - name: username
    value: workshop
  - name: password
    value: p
  - name: bearerToken
    value: ""
